import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export const metadata = {
  title: "Terms & Conditions — Storimac",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh flex-col bg-neutral-950 text-neutral-200">
      <SiteHeader />
      <main className="mx-auto w-full max-w-3xl flex-1 px-5 py-12">
        <h1 className="text-2xl font-bold text-white">Terms &amp; Conditions</h1>
        <p className="mt-2 text-xs text-neutral-500">Last updated: July 26, 2026</p>

        <section className="mt-8 space-y-6 text-sm leading-relaxed text-neutral-300">
          <div>
            <h2 className="mb-2 text-base font-semibold text-white">The service</h2>
            <p>
              Storimac is a guided story-development tool: an AI-assisted interview that helps you
              turn a story idea into a structured Story Foundation Document. By creating an
              account you agree to these terms.
            </p>
          </div>
          <div>
            <h2 className="mb-2 text-base font-semibold text-white">Your content</h2>
            <p>
              You own the stories you develop here. You grant us only the limited rights needed to
              operate the service: storing your content, and sending your interview messages to
              our AI provider (Anthropic) to generate responses. AI-generated suggestions are
              yours to use, adapt, or discard.
            </p>
          </div>
          <div>
            <h2 className="mb-2 text-base font-semibold text-white">Acceptable use</h2>
            <p>
              Don&apos;t use Storimac to violate the law, infringe others&apos; intellectual
              property, or attempt to disrupt the service or other users&apos; workspaces. Free
              tier limits (one user, one workspace, one canvas) are enforced by the service and
              must not be circumvented.
            </p>
          </div>
          <div>
            <h2 className="mb-2 text-base font-semibold text-white">AI output</h2>
            <p>
              Editor responses are generated by a large language model. They can be wrong,
              incomplete, or unsuitable for your story. You are responsible for the creative and
              factual judgment applied to anything you keep.
            </p>
          </div>
          <div>
            <h2 className="mb-2 text-base font-semibold text-white">Availability & changes</h2>
            <p>
              The service is provided as-is, without warranty. We may change or discontinue
              features; for material changes to these terms we will update this page and the
              &quot;last updated&quot; date above.
            </p>
          </div>
          <div>
            <h2 className="mb-2 text-base font-semibold text-white">Contact</h2>
            <p>Questions about these terms: hello@storimac.app.</p>
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
